In [1]:
import numpy as np

### Scenario 1

In [10]:
a = np.arange(8).reshape(2, 4)
b = np.arange(8, 16).reshape(2, 4)
print(a)
print(b)
a+b

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

### Scenario 2

In [17]:
a1= np.arange(4).reshape(1, 4)
b1 = np.arange(8,16).reshape(2, 4)

print("a1 : ",a1)
print("b1 : ",b1,"\n")

print("a1 + b1 : ",a1 + b1)

a1 :  [[0 1 2 3]]
b1 :  [[ 8  9 10 11]
 [12 13 14 15]] 

a1 + b1 :  [[ 8 10 12 14]
 [12 14 16 18]]


### Scenario 3

In [19]:
a2 = np.arange(2, 3)
b2 = np.arange(8).reshape(2, 4)
print("a2 : ",a1)
print("b2 : ",b1,"\n")

print("a2 + b2 : ",a1 + b1)

a2 :  [[0 1 2 3]]
b2 :  [[ 8  9 10 11]
 [12 13 14 15]] 

a2 + b2 :  [[ 8 10 12 14]
 [12 14 16 18]]
