In [1]:
import numpy as np


In [2]:
np.random.random()

0.46573326467564036

In [3]:
np.random.seed(1)    # it fix the value of random values
np.random.random()

0.417022004702574

In [4]:
np.random.seed(3)  # it fix the value of random values
np.random.random()

0.5507979025745755

In [5]:
print(np.random.random())
np.random.seed(1)
print(np.random.random())
print(np.random.random())

0.7081478226181048
0.417022004702574
0.7203244934421581


In [7]:
np.random.uniform(3, 10)  # it returns random value between given range 

5.116328008422879

In [9]:
np.random.uniform(1,100,10)  # using third parameter we can make array of define number of element of array

array([ 3.71137173, 67.37628351, 42.31317543, 56.31029302, 14.89830692,
       20.61204742, 80.2737123 , 96.857896  , 32.02899364, 69.53993895])

In [15]:
np.random.randint(1, 10) # it returns integer value from given range  

9

In [16]:
np.random.randint(1, 10, 5)

array([2, 5, 1, 4, 3])

In [18]:
a = np.random.randint(1, 10, 6)
a

array([7, 4, 8, 8, 5, 6])

In [19]:
np.max(a)

8

In [20]:
np.min(a)

4

In [21]:
np.argmax(a)

2

In [22]:
np.argmin(a)

1

### if we convert odd number into -1 

##### method 1

In [27]:
a[a%2 == 1]= -1

In [26]:
a

array([-1,  4,  8,  8, -1,  6])

##### method 2

In [32]:
b = np.random.randint(1, 50, 6)
b

array([29, 11, 47, 33, 25, 24])

In [33]:
np.where(b%2==1, -1, a)

array([-1, -1, -1, -1, -1,  6])

#### replace odd number with 1 and even with 0

In [34]:
np.where(b%2==1, 1, 0)

array([1, 1, 1, 1, 1, 0])

### sorting the array

In [46]:
c = np.random.randint(1, 50, 10)
c

array([31, 37, 40,  8, 46,  5, 49, 19, 33, 14])

In [47]:
c = np.sort(c)

In [48]:
c

array([ 5,  8, 14, 19, 31, 33, 37, 40, 46, 49])

## Find Percentile (only possible with sorted array)

In [50]:
d = np.random.randint(1, 50, 10)
d

array([ 2, 31, 42, 25, 19, 34,  3, 45, 29, 40])

In [52]:
d = np.sort(d)
d

array([ 2,  3, 19, 25, 29, 31, 34, 40, 42, 45])

In [71]:
n = 60
np.percentile(d, 60)  # it returns the value of nth percentile 

SyntaxError: invalid syntax (3386638739.py, line 1)