# Creating a Numpy Array 


In [1]:
import numpy as np 

## different functions to create array with differant way 

### 1) Using np.array()

In [8]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [9]:
arr0 = np.array([[1, 2, 3],[4, 5, 6]])
arr0

array([[1, 2, 3],
       [4, 5, 6]])

### 2) np.zeros/ones/empty/random()

In [5]:
arr1 = np.zeros((2,3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr2 = np.ones((3,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr3 = np.identity(5)
arr3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 3) np.arange()

In [13]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr5 = np.arange(5, 16, 2)
arr5

array([ 5,  7,  9, 11, 13, 15])

### 4) Using np.linspace()

In [15]:
arr6 = np.linspace(10, 20, 10)
arr6 # basicaslly there is a equal distance between al elements

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
arr7 = arr6.copy()