# Indexing, Slicing, and Iteration

### 1) Indexing 

In [2]:
import numpy as np


In [3]:

arr = np.arange(8).reshape(2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
arr1 = np.arange(1,6)
arr1

array([1, 2, 3, 4, 5])

In [7]:
arr1[3]

4

In [8]:
arr1[2:4]

array([3, 4])

In [9]:
arr1[-1]

5

In [10]:
arr[1]

array([4, 5, 6, 7])

In [12]:
arr2 = np.arange(24).reshape(6,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
arr2[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [14]:
arr2[2:4, 1:3] 

array([[ 9, 10],
       [13, 14]])

### print or access all elements of array 


In [15]:
for i in arr:
    print(i)
    

[0 1 2 3]
[4 5 6 7]


### print all elements and subelements of array

In [ ]:
for i in np.n