In [3]:
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([4, 5, 6, 7, 8, 9])
arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

In [5]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [6]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [9]:
arr2>6

array([False, False, False,  True,  True,  True])

## Find dot Product

In [10]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)
arr3.dot(arr4)  # finding a dot product of matrix

array([[ 28,  31],
       [100, 112]])

In [11]:
arr1.dot(arr4)

ValueError: shapes (6,) and (3,2) not aligned: 6 (dim 0) != 3 (dim 0)

In [12]:
arr4.max()  # find maximum values from arr4

11

In [13]:
arr4.min()  # find minimum values from arr4

6

In [14]:
arr4.min(axis=0)  # find minimum values for row from arr4

array([6, 7])

In [15]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [16]:
arr4.sum()


51

In [17]:
arr4.sum(axis = 0)  # sum of all columns

array([24, 27])

In [19]:
arr4.mean() # mean of all values arr4

8.5

In [20]:
arr4.std()  # standard deviation

1.707825127659933

In [21]:
np.sin(arr4)  # find sin 

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [22]:
np.median(arr4)

8.5

In [23]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])