## reshaping numpy array 

### 1) ravel
### 2) reshape
### 3) transpose
### 4) stacking 
### 5) splitting



In [1]:
import numpy as np


In [2]:
arr = np.arange(6,12).reshape(3,2)
arr

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [3]:
arr.ravel()   # this function help to convert into single dimentional array from any dimentional array

array([ 6,  7,  8,  9, 10, 11])

In [4]:
arr.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [5]:
# ** Stacking : used to combine two arrays
arr1 = np.arange(12, 18).reshape(2, 3)
arr2 = np.arange(18, 24).reshape(2,3)
arr1

array([[12, 13, 14],
       [15, 16, 17]])

In [6]:
arr2

array([[18, 19, 20],
       [21, 22, 23]])

In [8]:
np.hstack((arr1, arr2))   # horizontally stack

array([[12, 13, 14, 18, 19, 20],
       [15, 16, 17, 21, 22, 23]])

In [10]:
np.vstack((arr1, arr2))    # vartically stack

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

## Spliting of array

In [14]:
np.hsplit(arr1, 3)  # horizontally split

[array([[12],
        [15]]),
 array([[13],
        [16]]),
 array([[14],
        [17]])]

In [17]:
np.vsplit(arr1, 2)    # vartically split

[array([[12, 13, 14]]), array([[15, 16, 17]])]

In [18]:
arr3 = np.arange(1, 9).reshape(2, 4)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.hsplit(arr3, 2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]