In [1]:
import numpy as np

In [2]:
arr = np.random.randint(low = 1, high = 100, size = 20 ).reshape(4,5)
arr

array([[95, 45, 63, 31, 76],
       [94, 78, 82, 96, 38],
       [59, 48, 72, 11, 53],
       [63, 58, 67, 65, 21]])

In [3]:
arr>50   # get vslues in the form of boolean array

array([[ True, False,  True, False,  True],
       [ True,  True,  True,  True, False],
       [ True, False,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [4]:
arr[arr>50]   

array([95, 63, 76, 94, 78, 82, 96, 59, 72, 53, 63, 58, 67, 65])

In [5]:
arr[(arr>50) & (arr%2 != 0 )]   # take those items which is greater than 50 and it is odd

array([95, 63, 59, 53, 63, 67, 65])

In [6]:
 arr[(arr>50) and (arr%2 != 0 )]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [12]:
arr[(arr>50) & (arr%2 != 0 )] = 999

In [13]:
arr

array([[999,  45, 999,  31,  76],
       [ 94,  78,  82,  96,  38],
       [999,  48,  72,  11, 999],
       [999,  58, 999, 999,  21]])